"""SQLite schema for weather ensemble research data."""

from __future__ import annotations

import sqlite3
from pathlib import Path

from weather_quant.paths import PROJECT_ROOT


DEFAULT_DB_PATH = PROJECT_ROOT / "data" / "weather.db"


SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS schema_comments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  object_type TEXT NOT NULL,
  object_name TEXT NOT NULL,
  column_name TEXT,
  comment TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS weather_cities (
  city_id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  latitude REAL NOT NULL,
  longitude REAL NOT NULL,
  timezone TEXT NOT NULL,
  settlement_station TEXT,
  station_id TEXT,
  metar_source TEXT,
  forecast_granularity TEXT NOT NULL,
  settlement_unit TEXT NOT NULL,
  weather_models_json TEXT NOT NULL,
  model_weights_json TEXT NOT NULL,
  model_error_std REAL NOT NULL,
  min_distribution_std REAL NOT NULL,
  elevation REAL,
  cell_selection TEXT,
  is_builtin INTEGER NOT NULL DEFAULT 0,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS weather_ensemble_runs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  run_key TEXT NOT NULL,
  provider TEXT NOT NULL,
  model TEXT NOT NULL,
  run_time TEXT,
  initialization_time TEXT,
  city_id TEXT NOT NULL,
  target_date TEXT NOT NULL,
  kind TEXT NOT NULL,
  latitude REAL NOT NULL,
  longitude REAL NOT NULL,
  timezone TEXT NOT NULL,
  settlement_station TEXT,
  station_id TEXT,
  metar_source TEXT,
  forecast_granularity TEXT NOT NULL,
  member_count INTEGER NOT NULL,
  fetched_at TEXT NOT NULL,
  raw_payload_json TEXT,
  payload_hash TEXT
);

CREATE TABLE IF NOT EXISTS weather_ensemble_members (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  run_key TEXT NOT NULL,
  member_id TEXT NOT NULL,
  target_date TEXT NOT NULL,
  kind TEXT NOT NULL,
  daily_value REAL NOT NULL,
  unit TEXT NOT NULL,
  bucket_label TEXT,
  bucket_key TEXT,
  raw_hourly_json TEXT,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS weather_bucket_probabilities (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  run_key TEXT NOT NULL,
  bucket_label TEXT NOT NULL,
  bucket_key TEXT NOT NULL,
  hit_count INTEGER NOT NULL,
  probability REAL NOT NULL,
  total_members INTEGER NOT NULL,
  unmatched_count INTEGER NOT NULL,
  empirical_mean REAL,
  empirical_std REAL,
  p10 REAL,
  p50 REAL,
  p90 REAL,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS weather_market_snapshots (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  market_snapshot_group TEXT NOT NULL,
  market_slug TEXT,
  condition_id TEXT,
  outcome TEXT NOT NULL,
  token_id TEXT,
  bucket_label TEXT NOT NULL,
  bucket_key TEXT NOT NULL,
  price REAL,
  best_bid REAL,
  best_ask REAL,
  midpoint REAL,
  spread REAL,
  ask_sum REAL,
  bid_sum REAL,
  midpoint_sum REAL,
  is_overround INTEGER NOT NULL,
  fetched_at TEXT NOT NULL,
  raw_payload_json TEXT
);

CREATE TABLE IF NOT EXISTS weather_signal_snapshots (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  run_key TEXT NOT NULL,
  market_snapshot_group TEXT,
  outcome TEXT NOT NULL,
  bucket_key TEXT NOT NULL,
  ensemble_probability REAL NOT NULL,
  market_midpoint REAL,
  best_bid REAL,
  best_ask REAL,
  executable_entry_cost REAL,
  fee REAL,
  expected_exit_cost REAL,
  edge REAL NOT NULL,
  recommendation TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS weather_settlement_import_runs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  import_run_key TEXT NOT NULL UNIQUE,
  city_id TEXT NOT NULL,
  target_date TEXT NOT NULL,
  kind TEXT NOT NULL,
  provider TEXT NOT NULL,
  station_id TEXT,
  status TEXT NOT NULL,
  started_at TEXT NOT NULL,
  finished_at TEXT NOT NULL,
  error_message TEXT,
  raw_request_json TEXT,
  raw_payload_json TEXT
);

CREATE TABLE IF NOT EXISTS weather_settlements (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  settlement_key TEXT NOT NULL UNIQUE,
  import_run_key TEXT,
  city_id TEXT NOT NULL,
  city_name TEXT NOT NULL,
  target_date TEXT NOT NULL,
  kind TEXT NOT NULL,
  station_id TEXT,
  settlement_station TEXT,
  source_provider TEXT NOT NULL,
  source_url TEXT,
  observed_value REAL NOT NULL,
  unit TEXT NOT NULL,
  bucket_label TEXT,
  bucket_key TEXT,
  observation_count INTEGER NOT NULL,
  observation_start TEXT,
  observation_end TEXT,
  status TEXT NOT NULL,
  imported_at TEXT NOT NULL,
  raw_payload_json TEXT
);

CREATE TABLE IF NOT EXISTS weather_signal_outcomes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  signal_snapshot_id INTEGER NOT NULL,
  run_key TEXT NOT NULL,
  settlement_key TEXT NOT NULL,
  city_id TEXT NOT NULL,
  target_date TEXT NOT NULL,
  kind TEXT NOT NULL,
  outcome TEXT NOT NULL,
  bucket_key TEXT NOT NULL,
  actual_bucket_key TEXT,
  ensemble_probability REAL NOT NULL,
  market_midpoint REAL,
  edge REAL NOT NULL,
  recommendation TEXT NOT NULL,
  won INTEGER NOT NULL,
  brier_score REAL NOT NULL,
  probability_error REAL NOT NULL,
  created_at TEXT NOT NULL,
  UNIQUE(signal_snapshot_id, settlement_key)
);

CREATE TABLE IF NOT EXISTS weather_paper_accounts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  account_key TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  initial_cash REAL NOT NULL,
  cash_balance REAL NOT NULL,
  status TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  raw_config_json TEXT
);

CREATE TABLE IF NOT EXISTS weather_paper_orders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  order_key TEXT NOT NULL UNIQUE,
  account_key TEXT NOT NULL,
  signal_snapshot_id INTEGER,
  run_key TEXT,
  market_snapshot_group TEXT,
  city_id TEXT,
  city_name TEXT,
  target_date TEXT,
  kind TEXT,
  settlement_station TEXT,
  station_id TEXT,
  metar_source TEXT,
  market_slug TEXT,
  condition_id TEXT,
  outcome TEXT NOT NULL,
  bucket_label TEXT NOT NULL,
  bucket_key TEXT NOT NULL,
  token_id TEXT,
  side TEXT NOT NULL,
  order_type TEXT NOT NULL,
  stake_usdc REAL NOT NULL,
  filled_shares REAL NOT NULL DEFAULT 0,
  vwap REAL,
  average_price REAL,
  fee REAL NOT NULL DEFAULT 0,
  net_cost REAL NOT NULL DEFAULT 0,
  edge REAL,
  ensemble_probability REAL,
  executable_entry_cost REAL,
  expected_exit_cost REAL,
  best_bid REAL,
  best_ask REAL,
  spread REAL,
  ask_depth REAL,
  status TEXT NOT NULL,
  reject_reason TEXT,
  created_at TEXT NOT NULL,
  raw_signal_json TEXT,
  raw_preview_json TEXT
);

CREATE TABLE IF NOT EXISTS weather_paper_trades (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  trade_key TEXT NOT NULL UNIQUE,
  account_key TEXT NOT NULL,
  order_key TEXT NOT NULL,
  position_key TEXT NOT NULL,
  side TEXT NOT NULL,
  outcome TEXT NOT NULL,
  bucket_label TEXT NOT NULL,
  bucket_key TEXT NOT NULL,
  token_id TEXT,
  shares REAL NOT NULL,
  price REAL NOT NULL,
  notional REAL NOT NULL,
  fee REAL NOT NULL,
  net_cost REAL NOT NULL,
  traded_at TEXT NOT NULL,
  raw_fill_json TEXT
);

CREATE TABLE IF NOT EXISTS weather_paper_positions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  position_key TEXT NOT NULL UNIQUE,
  account_key TEXT NOT NULL,
  city_id TEXT,
  city_name TEXT,
  target_date TEXT,
  kind TEXT,
  market_snapshot_group TEXT,
  market_slug TEXT,
  condition_id TEXT,
  outcome TEXT NOT NULL,
  bucket_label TEXT NOT NULL,
  bucket_key TEXT NOT NULL,
  token_id TEXT,
  settlement_station TEXT,
  station_id TEXT,
  metar_source TEXT,
  open_shares REAL NOT NULL,
  total_cost REAL NOT NULL,
  average_entry_price REAL,
  realized_pnl REAL NOT NULL DEFAULT 0,
  status TEXT NOT NULL,
  opened_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  closed_at TEXT
);

CREATE TABLE IF NOT EXISTS weather_paper_position_marks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  mark_key TEXT NOT NULL UNIQUE,
  account_key TEXT NOT NULL,
  position_key TEXT NOT NULL,
  token_id TEXT,
  city_id TEXT,
  target_date TEXT,
  kind TEXT,
  outcome TEXT NOT NULL,
  bucket_label TEXT NOT NULL,
  bucket_key TEXT NOT NULL,
  open_shares REAL NOT NULL,
  total_cost REAL NOT NULL,
  average_entry_price REAL,
  best_bid REAL,
  best_ask REAL,
  midpoint REAL,
  spread REAL,
  bid_depth REAL,
  ask_depth REAL,
  mark_value REAL NOT NULL,
  liquidation_value REAL NOT NULL,
  cashout_ratio REAL,
  unrealized_pnl REAL NOT NULL,
  executable_pnl REAL NOT NULL,
  exit_signal TEXT NOT NULL,
  warning TEXT,
  fetched_at TEXT NOT NULL,
  raw_orderbook_json TEXT
);

CREATE TABLE IF NOT EXISTS weather_paper_position_settlements (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  settlement_record_key TEXT NOT NULL UNIQUE,
  account_key TEXT NOT NULL,
  position_key TEXT NOT NULL,
  settlement_key TEXT NOT NULL,
  city_id TEXT NOT NULL,
  target_date TEXT NOT NULL,
  kind TEXT NOT NULL,
  outcome TEXT NOT NULL,
  bucket_label TEXT NOT NULL,
  bucket_key TEXT NOT NULL,
  actual_bucket_key TEXT,
  observed_value REAL NOT NULL,
  unit TEXT NOT NULL,
  shares REAL NOT NULL,
  total_cost REAL NOT NULL,
  payout REAL NOT NULL,
  realized_pnl REAL NOT NULL,
  settled_at TEXT NOT NULL,
  raw_payload_json TEXT
);
"""


SCHEMA_COMMENTS: tuple[tuple[str, str, str | None, str], ...] = (
    ("table", "schema_comments", None, "SQLite 对象中文说明表"),
    ("column", "schema_comments", "id", "自增主键"),
    ("column", "schema_comments", "object_type", "对象类型，table 或 column"),
    ("column", "schema_comments", "object_name", "表名或对象名"),
    ("column", "schema_comments", "column_name", "字段名，表说明时为空"),
    ("column", "schema_comments", "comment", "中文说明文本"),
    ("table", "weather_cities", None, "可编辑城市/结算点配置"),
    ("column", "weather_cities", "city_id", "城市配置 ID，用于前端选择和 API 查询"),
    ("column", "weather_cities", "name", "城市或点位显示名称"),
    ("column", "weather_cities", "latitude", "请求纬度"),
    ("column", "weather_cities", "longitude", "请求经度"),
    ("column", "weather_cities", "timezone", "聚合天气数据使用的时区"),
    ("column", "weather_cities", "settlement_station", "市场结算站说明"),
    ("column", "weather_cities", "station_id", "站点代码，例如 METAR ID"),
    ("column", "weather_cities", "metar_source", "站点观测来源"),
    ("column", "weather_cities", "forecast_granularity", "预报粒度，city 或 station"),
    ("column", "weather_cities", "settlement_unit", "结算温度单位，F 或 C"),
    ("column", "weather_cities", "weather_models_json", "默认天气模型 JSON 数组"),
    ("column", "weather_cities", "model_weights_json", "模型权重 JSON 对象"),
    ("column", "weather_cities", "model_error_std", "概率模型误差标准差"),
    ("column", "weather_cities", "min_distribution_std", "概率分布最小标准差"),
    ("column", "weather_cities", "elevation", "Open-Meteo 海拔覆盖参数"),
    ("column", "weather_cities", "cell_selection", "Open-Meteo 格点选择参数"),
    ("column", "weather_cities", "is_builtin", "是否为内置默认城市"),
    ("column", "weather_cities", "sort_order", "前端排序序号"),
    ("column", "weather_cities", "created_at", "创建时间"),
    ("column", "weather_cities", "updated_at", "更新时间"),
    ("table", "weather_ensemble_runs", None, "一次天气集合预报初始化运行"),
    ("column", "weather_ensemble_runs", "id", "自增主键"),
    ("column", "weather_ensemble_runs", "run_key", "运行文本键，用于关联 member/probability/signal"),
    ("column", "weather_ensemble_runs", "provider", "数据提供方，例如 open-meteo"),
    ("column", "weather_ensemble_runs", "model", "集合预报模型"),
    ("column", "weather_ensemble_runs", "run_time", "模型运行时间"),
    ("column", "weather_ensemble_runs", "initialization_time", "模型初始化时间"),
    ("column", "weather_ensemble_runs", "city_id", "城市配置 ID"),
    ("column", "weather_ensemble_runs", "target_date", "目标结算日期"),
    ("column", "weather_ensemble_runs", "kind", "温度类型 high 或 low"),
    ("column", "weather_ensemble_runs", "latitude", "请求纬度"),
    ("column", "weather_ensemble_runs", "longitude", "请求经度"),
    ("column", "weather_ensemble_runs", "timezone", "聚合使用的时区"),
    ("column", "weather_ensemble_runs", "settlement_station", "市场结算站说明"),
    ("column", "weather_ensemble_runs", "station_id", "结算站代码"),
    ("column", "weather_ensemble_runs", "metar_source", "站点观测来源"),
    ("column", "weather_ensemble_runs", "forecast_granularity", "预报粒度，city 或 station"),
    ("column", "weather_ensemble_runs", "member_count", "可用 ensemble member 数量"),
    ("column", "weather_ensemble_runs", "fetched_at", "拉取时间"),
    ("column", "weather_ensemble_runs", "raw_payload_json", "原始响应 JSON"),
    ("column", "weather_ensemble_runs", "payload_hash", "原始响应哈希"),
    ("table", "weather_ensemble_members", None, "集合预报 member 的日高温/低温结果"),
    ("column", "weather_ensemble_members", "id", "自增主键"),
    ("column", "weather_ensemble_members", "run_key", "所属运行文本键"),
    ("column", "weather_ensemble_members", "member_id", "member 标识"),
    ("column", "weather_ensemble_members", "target_date", "目标结算日期"),
    ("column", "weather_ensemble_members", "kind", "温度类型 high 或 low"),
    ("column", "weather_ensemble_members", "daily_value", "聚合后的日高温或日低温"),
    ("column", "weather_ensemble_members", "unit", "温度单位"),
    ("column", "weather_ensemble_members", "bucket_label", "命中的温度桶标签"),
    ("column", "weather_ensemble_members", "bucket_key", "命中的温度桶规范键"),
    ("column", "weather_ensemble_members", "raw_hourly_json", "该 member 当日小时数据 JSON"),
    ("column", "weather_ensemble_members", "created_at", "写入时间"),
    ("table", "weather_bucket_probabilities", None, "member 命中次数形成的桶概率"),
    ("column", "weather_bucket_probabilities", "id", "自增主键"),
    ("column", "weather_bucket_probabilities", "run_key", "所属运行文本键"),
    ("column", "weather_bucket_probabilities", "bucket_label", "温度桶标签"),
    ("column", "weather_bucket_probabilities", "bucket_key", "温度桶规范键"),
    ("column", "weather_bucket_probabilities", "hit_count", "命中 member 数量"),
    ("column", "weather_bucket_probabilities", "probability", "命中概率"),
    ("column", "weather_bucket_probabilities", "total_members", "总 member 数量"),
    ("column", "weather_bucket_probabilities", "unmatched_count", "未命中任何桶的 member 数量"),
    ("column", "weather_bucket_probabilities", "empirical_mean", "member 经验均值"),
    ("column", "weather_bucket_probabilities", "empirical_std", "member 经验标准差"),
    ("column", "weather_bucket_probabilities", "p10", "member 经验 10 分位"),
    ("column", "weather_bucket_probabilities", "p50", "member 经验 50 分位"),
    ("column", "weather_bucket_probabilities", "p90", "member 经验 90 分位"),
    ("column", "weather_bucket_probabilities", "created_at", "写入时间"),
    ("table", "weather_market_snapshots", None, "Polymarket 温度桶市场快照"),
    ("column", "weather_market_snapshots", "id", "自增主键"),
    ("column", "weather_market_snapshots", "market_snapshot_group", "同一次市场快照分组键"),
    ("column", "weather_market_snapshots", "market_slug", "Polymarket slug"),
    ("column", "weather_market_snapshots", "condition_id", "Polymarket condition id"),
    ("column", "weather_market_snapshots", "outcome", "市场 outcome 文本"),
    ("column", "weather_market_snapshots", "token_id", "CLOB token id"),
    ("column", "weather_market_snapshots", "bucket_label", "温度桶标签"),
    ("column", "weather_market_snapshots", "bucket_key", "温度桶规范键"),
    ("column", "weather_market_snapshots", "price", "市场价格"),
    ("column", "weather_market_snapshots", "best_bid", "最佳买价"),
    ("column", "weather_market_snapshots", "best_ask", "最佳卖价"),
    ("column", "weather_market_snapshots", "midpoint", "盘口中点"),
    ("column", "weather_market_snapshots", "spread", "买卖价差"),
    ("column", "weather_market_snapshots", "ask_sum", "同组 ask 概率和"),
    ("column", "weather_market_snapshots", "bid_sum", "同组 bid 概率和"),
    ("column", "weather_market_snapshots", "midpoint_sum", "同组 midpoint 概率和"),
    ("column", "weather_market_snapshots", "is_overround", "是否存在 overround"),
    ("column", "weather_market_snapshots", "fetched_at", "快照时间"),
    ("column", "weather_market_snapshots", "raw_payload_json", "原始市场数据 JSON"),
    ("table", "weather_signal_snapshots", None, "ensemble 概率与市场价格形成的信号快照"),
    ("column", "weather_signal_snapshots", "id", "自增主键"),
    ("column", "weather_signal_snapshots", "run_key", "所属运行文本键"),
    ("column", "weather_signal_snapshots", "market_snapshot_group", "对应市场快照分组键"),
    ("column", "weather_signal_snapshots", "outcome", "市场 outcome 文本"),
    ("column", "weather_signal_snapshots", "bucket_key", "温度桶规范键"),
    ("column", "weather_signal_snapshots", "ensemble_probability", "ensemble member 命中概率"),
    ("column", "weather_signal_snapshots", "market_midpoint", "市场中点价格"),
    ("column", "weather_signal_snapshots", "best_bid", "最佳买价"),
    ("column", "weather_signal_snapshots", "best_ask", "最佳卖价"),
    ("column", "weather_signal_snapshots", "executable_entry_cost", "可执行入场成本"),
    ("column", "weather_signal_snapshots", "fee", "单位合约估算费用"),
    ("column", "weather_signal_snapshots", "expected_exit_cost", "预期退出成本"),
    ("column", "weather_signal_snapshots", "edge", "扣除成本后的 edge"),
    ("column", "weather_signal_snapshots", "recommendation", "交易建议"),
    ("column", "weather_signal_snapshots", "created_at", "写入时间"),
    ("table", "weather_settlement_import_runs", None, "结算观测接口导入运行记录"),
    ("column", "weather_settlement_import_runs", "id", "自增主键"),
    ("column", "weather_settlement_import_runs", "import_run_key", "接口导入运行文本键"),
    ("column", "weather_settlement_import_runs", "city_id", "城市配置 ID"),
    ("column", "weather_settlement_import_runs", "target_date", "目标结算日期"),
    ("column", "weather_settlement_import_runs", "kind", "温度类型 high 或 low"),
    ("column", "weather_settlement_import_runs", "provider", "结算观测接口提供方"),
    ("column", "weather_settlement_import_runs", "station_id", "结算站代码"),
    ("column", "weather_settlement_import_runs", "status", "导入状态，success 或 failed"),
    ("column", "weather_settlement_import_runs", "started_at", "导入开始时间"),
    ("column", "weather_settlement_import_runs", "finished_at", "导入结束时间"),
    ("column", "weather_settlement_import_runs", "error_message", "失败原因"),
    ("column", "weather_settlement_import_runs", "raw_request_json", "接口请求参数 JSON"),
    ("column", "weather_settlement_import_runs", "raw_payload_json", "接口原始响应 JSON"),
    ("table", "weather_settlements", None, "天气市场最终结算观测结果"),
    ("column", "weather_settlements", "id", "自增主键"),
    ("column", "weather_settlements", "settlement_key", "结算结果文本键"),
    ("column", "weather_settlements", "import_run_key", "来源导入运行文本键"),
    ("column", "weather_settlements", "city_id", "城市配置 ID"),
    ("column", "weather_settlements", "city_name", "城市显示名称"),
    ("column", "weather_settlements", "target_date", "目标结算日期"),
    ("column", "weather_settlements", "kind", "温度类型 high 或 low"),
    ("column", "weather_settlements", "station_id", "结算站代码"),
    ("column", "weather_settlements", "settlement_station", "结算站说明"),
    ("column", "weather_settlements", "source_provider", "结算观测接口提供方"),
    ("column", "weather_settlements", "source_url", "结算观测接口 URL"),
    ("column", "weather_settlements", "observed_value", "实际观测到的结算温度"),
    ("column", "weather_settlements", "unit", "结算温度单位，F 或 C"),
    ("column", "weather_settlements", "bucket_label", "实际命中的温度桶标签"),
    ("column", "weather_settlements", "bucket_key", "实际命中的温度桶规范键"),
    ("column", "weather_settlements", "observation_count", "用于计算结算温度的观测数量"),
    ("column", "weather_settlements", "observation_start", "最早观测时间"),
    ("column", "weather_settlements", "observation_end", "最晚观测时间"),
    ("column", "weather_settlements", "status", "结算结果状态"),
    ("column", "weather_settlements", "imported_at", "导入时间"),
    ("column", "weather_settlements", "raw_payload_json", "接口原始响应 JSON"),
    ("table", "weather_signal_outcomes", None, "历史信号与结算结果匹配后的复盘结果"),
    ("column", "weather_signal_outcomes", "id", "自增主键"),
    ("column", "weather_signal_outcomes", "signal_snapshot_id", "信号快照自增 ID"),
    ("column", "weather_signal_outcomes", "run_key", "所属 ensemble 运行文本键"),
    ("column", "weather_signal_outcomes", "settlement_key", "匹配的结算结果文本键"),
    ("column", "weather_signal_outcomes", "city_id", "城市配置 ID"),
    ("column", "weather_signal_outcomes", "target_date", "目标结算日期"),
    ("column", "weather_signal_outcomes", "kind", "温度类型 high 或 low"),
    ("column", "weather_signal_outcomes", "outcome", "市场 outcome 文本"),
    ("column", "weather_signal_outcomes", "bucket_key", "信号对应温度桶规范键"),
    ("column", "weather_signal_outcomes", "actual_bucket_key", "实际命中温度桶规范键"),
    ("column", "weather_signal_outcomes", "ensemble_probability", "信号当时 ensemble 概率"),
    ("column", "weather_signal_outcomes", "market_midpoint", "信号当时市场中点价格"),
    ("column", "weather_signal_outcomes", "edge", "信号当时扣成本 edge"),
    ("column", "weather_signal_outcomes", "recommendation", "信号当时交易建议"),
    ("column", "weather_signal_outcomes", "won", "该 outcome 是否命中"),
    ("column", "weather_signal_outcomes", "brier_score", "该 outcome 的 Brier score"),
    ("column", "weather_signal_outcomes", "probability_error", "实际结果减预测概率"),
    ("column", "weather_signal_outcomes", "created_at", "写入时间"),
    ("table", "weather_paper_accounts", None, "虚拟盘账户资金表"),
    ("column", "weather_paper_accounts", "id", "自增主键"),
    ("column", "weather_paper_accounts", "account_key", "虚拟账户文本键"),
    ("column", "weather_paper_accounts", "name", "虚拟账户显示名称"),
    ("column", "weather_paper_accounts", "initial_cash", "账户初始虚拟资金"),
    ("column", "weather_paper_accounts", "cash_balance", "账户当前现金余额"),
    ("column", "weather_paper_accounts", "status", "账户状态"),
    ("column", "weather_paper_accounts", "created_at", "创建时间"),
    ("column", "weather_paper_accounts", "updated_at", "更新时间"),
    ("column", "weather_paper_accounts", "raw_config_json", "账户初始化配置 JSON"),
    ("table", "weather_paper_orders", None, "虚拟盘订单记录表"),
    ("column", "weather_paper_orders", "id", "自增主键"),
    ("column", "weather_paper_orders", "order_key", "虚拟订单文本键"),
    ("column", "weather_paper_orders", "account_key", "所属虚拟账户文本键"),
    ("column", "weather_paper_orders", "signal_snapshot_id", "来源信号快照自增 ID"),
    ("column", "weather_paper_orders", "run_key", "来源 ensemble 运行文本键"),
    ("column", "weather_paper_orders", "market_snapshot_group", "来源市场快照分组键"),
    ("column", "weather_paper_orders", "city_id", "城市配置 ID"),
    ("column", "weather_paper_orders", "city_name", "城市显示名称"),
    ("column", "weather_paper_orders", "target_date", "目标结算日期"),
    ("column", "weather_paper_orders", "kind", "温度类型 high 或 low"),
    ("column", "weather_paper_orders", "settlement_station", "结算站说明"),
    ("column", "weather_paper_orders", "station_id", "结算站代码"),
    ("column", "weather_paper_orders", "metar_source", "站点观测来源"),
    ("column", "weather_paper_orders", "market_slug", "Polymarket slug"),
    ("column", "weather_paper_orders", "condition_id", "Polymarket condition id"),
    ("column", "weather_paper_orders", "outcome", "市场 outcome 文本"),
    ("column", "weather_paper_orders", "bucket_label", "温度桶标签"),
    ("column", "weather_paper_orders", "bucket_key", "温度桶规范键"),
    ("column", "weather_paper_orders", "token_id", "CLOB token id"),
    ("column", "weather_paper_orders", "side", "虚拟交易方向"),
    ("column", "weather_paper_orders", "order_type", "虚拟订单类型"),
    ("column", "weather_paper_orders", "stake_usdc", "计划投入虚拟 USDC 金额"),
    ("column", "weather_paper_orders", "filled_shares", "虚拟成交 YES 份额"),
    ("column", "weather_paper_orders", "vwap", "虚拟成交均价"),
    ("column", "weather_paper_orders", "average_price", "含 fee 后平均入场成本"),
    ("column", "weather_paper_orders", "fee", "虚拟成交估算 fee"),
    ("column", "weather_paper_orders", "net_cost", "含 fee 后虚拟买入净成本"),
    ("column", "weather_paper_orders", "edge", "按可执行成交成本计算的 edge"),
    ("column", "weather_paper_orders", "ensemble_probability", "来源模型概率"),
    ("column", "weather_paper_orders", "executable_entry_cost", "可执行入场成交均价"),
    ("column", "weather_paper_orders", "expected_exit_cost", "预期退出成本"),
    ("column", "weather_paper_orders", "best_bid", "买入时最佳买价"),
    ("column", "weather_paper_orders", "best_ask", "买入时最佳卖价"),
    ("column", "weather_paper_orders", "spread", "买入时买卖价差"),
    ("column", "weather_paper_orders", "ask_depth", "买入时可见 ask 深度"),
    ("column", "weather_paper_orders", "status", "虚拟订单状态"),
    ("column", "weather_paper_orders", "reject_reason", "虚拟订单拒绝原因"),
    ("column", "weather_paper_orders", "created_at", "创建时间"),
    ("column", "weather_paper_orders", "raw_signal_json", "来源信号 JSON"),
    ("column", "weather_paper_orders", "raw_preview_json", "虚拟买入预览 JSON"),
    ("table", "weather_paper_trades", None, "虚拟盘成交明细表"),
    ("column", "weather_paper_trades", "id", "自增主键"),
    ("column", "weather_paper_trades", "trade_key", "虚拟成交文本键"),
    ("column", "weather_paper_trades", "account_key", "所属虚拟账户文本键"),
    ("column", "weather_paper_trades", "order_key", "来源虚拟订单文本键"),
    ("column", "weather_paper_trades", "position_key", "聚合持仓文本键"),
    ("column", "weather_paper_trades", "side", "虚拟成交方向"),
    ("column", "weather_paper_trades", "outcome", "市场 outcome 文本"),
    ("column", "weather_paper_trades", "bucket_label", "温度桶标签"),
    ("column", "weather_paper_trades", "bucket_key", "温度桶规范键"),
    ("column", "weather_paper_trades", "token_id", "CLOB token id"),
    ("column", "weather_paper_trades", "shares", "虚拟成交 YES 份额"),
    ("column", "weather_paper_trades", "price", "虚拟成交均价"),
    ("column", "weather_paper_trades", "notional", "虚拟成交名义金额"),
    ("column", "weather_paper_trades", "fee", "虚拟成交估算 fee"),
    ("column", "weather_paper_trades", "net_cost", "含 fee 后虚拟成交成本"),
    ("column", "weather_paper_trades", "traded_at", "虚拟成交时间"),
    ("column", "weather_paper_trades", "raw_fill_json", "虚拟成交估算 JSON"),
    ("table", "weather_paper_positions", None, "虚拟盘持仓聚合表"),
    ("column", "weather_paper_positions", "id", "自增主键"),
    ("column", "weather_paper_positions", "position_key", "虚拟持仓文本键"),
    ("column", "weather_paper_positions", "account_key", "所属虚拟账户文本键"),
    ("column", "weather_paper_positions", "city_id", "城市配置 ID"),
    ("column", "weather_paper_positions", "city_name", "城市显示名称"),
    ("column", "weather_paper_positions", "target_date", "目标结算日期"),
    ("column", "weather_paper_positions", "kind", "温度类型 high 或 low"),
    ("column", "weather_paper_positions", "market_snapshot_group", "来源市场快照分组键"),
    ("column", "weather_paper_positions", "market_slug", "Polymarket slug"),
    ("column", "weather_paper_positions", "condition_id", "Polymarket condition id"),
    ("column", "weather_paper_positions", "outcome", "市场 outcome 文本"),
    ("column", "weather_paper_positions", "bucket_label", "温度桶标签"),
    ("column", "weather_paper_positions", "bucket_key", "温度桶规范键"),
    ("column", "weather_paper_positions", "token_id", "CLOB token id"),
    ("column", "weather_paper_positions", "settlement_station", "结算站说明"),
    ("column", "weather_paper_positions", "station_id", "结算站代码"),
    ("column", "weather_paper_positions", "metar_source", "站点观测来源"),
    ("column", "weather_paper_positions", "open_shares", "未结算或未平仓 YES 份额"),
    ("column", "weather_paper_positions", "total_cost", "当前持仓分摊成本"),
    ("column", "weather_paper_positions", "average_entry_price", "平均入场成本"),
    ("column", "weather_paper_positions", "realized_pnl", "已实现盈亏"),
    ("column", "weather_paper_positions", "status", "持仓状态"),
    ("column", "weather_paper_positions", "opened_at", "首次开仓时间"),
    ("column", "weather_paper_positions", "updated_at", "更新时间"),
    ("column", "weather_paper_positions", "closed_at", "关闭或结算时间"),
    ("table", "weather_paper_position_marks", None, "虚拟盘持仓盘口轮询估值快照表"),
    ("column", "weather_paper_position_marks", "id", "自增主键"),
    ("column", "weather_paper_position_marks", "mark_key", "盘口估值快照文本键"),
    ("column", "weather_paper_position_marks", "account_key", "所属虚拟账户文本键"),
    ("column", "weather_paper_position_marks", "position_key", "虚拟持仓文本键"),
    ("column", "weather_paper_position_marks", "token_id", "CLOB token id"),
    ("column", "weather_paper_position_marks", "city_id", "城市配置 ID"),
    ("column", "weather_paper_position_marks", "target_date", "目标结算日期"),
    ("column", "weather_paper_position_marks", "kind", "温度类型 high 或 low"),
    ("column", "weather_paper_position_marks", "outcome", "市场 outcome 文本"),
    ("column", "weather_paper_position_marks", "bucket_label", "温度桶标签"),
    ("column", "weather_paper_position_marks", "bucket_key", "温度桶规范键"),
    ("column", "weather_paper_position_marks", "open_shares", "轮询时未平仓 YES 份额"),
    ("column", "weather_paper_position_marks", "total_cost", "轮询时持仓成本"),
    ("column", "weather_paper_position_marks", "average_entry_price", "平均入场成本"),
    ("column", "weather_paper_position_marks", "best_bid", "轮询时最佳买价"),
    ("column", "weather_paper_position_marks", "best_ask", "轮询时最佳卖价"),
    ("column", "weather_paper_position_marks", "midpoint", "轮询时盘口中点"),
    ("column", "weather_paper_position_marks", "spread", "轮询时买卖价差"),
    ("column", "weather_paper_position_marks", "bid_depth", "轮询时可见 bid 深度"),
    ("column", "weather_paper_position_marks", "ask_depth", "轮询时可见 ask 深度"),
    ("column", "weather_paper_position_marks", "mark_value", "按盘口中点估算的持仓价值"),
    ("column", "weather_paper_position_marks", "liquidation_value", "按订单簿市价卖出估算的可兑现净值"),
    ("column", "weather_paper_position_marks", "cashout_ratio", "可兑现净值相对 mark value 的比例"),
    ("column", "weather_paper_position_marks", "unrealized_pnl", "按 mark value 计算的未实现盈亏"),
    ("column", "weather_paper_position_marks", "executable_pnl", "按可兑现净值计算的未实现盈亏"),
    ("column", "weather_paper_position_marks", "exit_signal", "提前卖出预览信号"),
    ("column", "weather_paper_position_marks", "warning", "盘口刷新警告或拒绝原因"),
    ("column", "weather_paper_position_marks", "fetched_at", "盘口刷新时间"),
    ("column", "weather_paper_position_marks", "raw_orderbook_json", "原始订单簿 JSON"),
    ("table", "weather_paper_position_settlements", None, "虚拟盘持仓结算结果表"),
    ("column", "weather_paper_position_settlements", "id", "自增主键"),
    ("column", "weather_paper_position_settlements", "settlement_record_key", "虚拟持仓结算文本键"),
    ("column", "weather_paper_position_settlements", "account_key", "所属虚拟账户文本键"),
    ("column", "weather_paper_position_settlements", "position_key", "虚拟持仓文本键"),
    ("column", "weather_paper_position_settlements", "settlement_key", "匹配的结算结果文本键"),
    ("column", "weather_paper_position_settlements", "city_id", "城市配置 ID"),
    ("column", "weather_paper_position_settlements", "target_date", "目标结算日期"),
    ("column", "weather_paper_position_settlements", "kind", "温度类型 high 或 low"),
    ("column", "weather_paper_position_settlements", "outcome", "市场 outcome 文本"),
    ("column", "weather_paper_position_settlements", "bucket_label", "温度桶标签"),
    ("column", "weather_paper_position_settlements", "bucket_key", "持仓温度桶规范键"),
    ("column", "weather_paper_position_settlements", "actual_bucket_key", "实际命中温度桶规范键"),
    ("column", "weather_paper_position_settlements", "observed_value", "实际观测到的结算温度"),
    ("column", "weather_paper_position_settlements", "unit", "结算温度单位，F 或 C"),
    ("column", "weather_paper_position_settlements", "shares", "参与结算的 YES 份额"),
    ("column", "weather_paper_position_settlements", "total_cost", "参与结算的持仓成本"),
    ("column", "weather_paper_position_settlements", "payout", "虚拟结算兑付金额"),
    ("column", "weather_paper_position_settlements", "realized_pnl", "虚拟结算已实现盈亏"),
    ("column", "weather_paper_position_settlements", "settled_at", "虚拟结算时间"),
    ("column", "weather_paper_position_settlements", "raw_payload_json", "虚拟结算详情 JSON"),
)


class ClosingConnection(sqlite3.Connection):
    """SQLite connection that closes when used as a context manager."""

    def __exit__(self, exc_type, exc_value, traceback) -> bool:  # noqa: ANN001
        super().__exit__(exc_type, exc_value, traceback)
        self.close()
        return False


def connect_database(path: Path | str | None = None) -> sqlite3.Connection:
    database_path = Path(path).expanduser() if path else DEFAULT_DB_PATH
    database_path.parent.mkdir(parents=True, exist_ok=True)
    connection = sqlite3.connect(database_path, factory=ClosingConnection)
    connection.row_factory = sqlite3.Row
    return connection


def init_database(path: Path | str | None = None) -> Path:
    database_path = Path(path).expanduser() if path else DEFAULT_DB_PATH
    with connect_database(database_path) as connection:
        connection.executescript(SCHEMA_SQL)
        connection.execute("DELETE FROM schema_comments")
        connection.executemany(
            """
            INSERT INTO schema_comments (object_type, object_name, column_name, comment)
            VALUES (?, ?, ?, ?)
            """,
            SCHEMA_COMMENTS,
        )
        connection.commit()
    return database_path
